version: '3.9'
services:
  server:
    build: .
    ports:
      - '80:80'
    links:
      - db
  db:
    image: mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ab-final
      - MYSQL_USER=msmk
      - MYSQL_PASSWORD=er@jKXBhjALCD7mWNJ
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/