version: '3.9'
services:
  server:
    build: .
    ports:
      - '80:80'
    volumes:
      - ./${PWD}:/var/www/html
  # ngrok:
  #     image: ngrok/ngrok:latest
  #     restart: unless-stopped
  #     command:
  #       - "start"
  #       - "--all"
  #       - "--config"
  #       - "/etc/ngrok.yml"
  #     volumes:
  #       - ./ngrok.yml:/etc/ngrok.yml
  #     ports:
  #       - 4040:4040